spring.application.name=AparcaYA

spring.datasource.url=jdbc:postgresql://localhost:5432/AparcaYa2.0
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

geocodificacion.opencage.key=972b38cb8f6f43fc9203ecda67200ebd

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aparcaya.parkingtech@gmail.com
spring.mail.password=bnsw wtcn zqjh dunq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# =====================================================================
# JWT ? 24 horas en milisegundos (86400000 ms = 86400 s = 24 horas)
# =====================================================================
jwt.secret=AparcaYA2024SuperSecretKeyParaJWTQueDebeSerDe256BitsMinimo!!
jwt.expiration=86400000

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false